### ISSUE TITLE
Type expression parsed differently whether a builtin type is used or not.

### ISSUE THREAD

**Issue by danabr** [alpaca-lang/alpaca#110]
This code parses correctly:
````
type my_map = map atom atom
````

This one fails with `["syntax error before: ",[]]`:
````
type my_atom = atom
type my_map = map my_atom atom
````

This again parses fine:
````
type my_atom = atom
type my_map = map (my_atom) atom
````

i.e, `type my_map = map my_atom atom` is parsed as `type my_map = map (my_atom atom)` .

**Comment by j14159** [comment]
Sorry for getting to this late, lots of stuff going on between work and all things Alpaca :)

I just wanted to clarify that we do expect `type my_map atom atom` to fail parsing but `type my_map = map atom atom` should not.  This seems to agree with your work in PR #112, just confirming as the initial bug description differs.

The only things that should be permitted on the left-hand side of a type declaration are the type name itself and variables I think.  E.g. `type my_map = map atom atom` and `type my_map 'a = map atom 'a` seem fine to me but I'm not sure what is being declared by `type my_map atom atom`.  Anything I'm missing?

**Comment by j14159** [comment]
I figured it's what you meant but wanted to make sure I wasn't missing anything :)
