### ISSUE TITLE
Type specifications for top-level bindings

### ISSUE THREAD

**Issue by j14159** [alpaca-lang/alpaca#133]
I've been thinking of something relatively simple, e.g.

    val add: [int, int] -> int
    let add x y = x + y

    type option 'a = Some 'a | None

    val map 'a 'b: [option 'a, (['a] -> 'b)] -> option 'b
    let map Some a f = Some (f a)
    let map _ _ = None

We can attach the specs to binding defs, type the bindings themselves and then if a spec can unify with the inferred type, we use the provided spec.

For receivers maybe something like the following for a function that when spawned receives `'a`s and never terminates:

    val f 'a receives 'a: ['a] -> rec
    let f init_state =
      receive with
        next_state -> f next_state

None of the above addresses naming arguments for documentation purposes, e.g. in `map`'s case it would be good for a single docstring to be able to refer to each parameter with a single name to document the interface for users.

    val map 'a 'b: [option_in: option 'a, f: (['a] -> 'b] -> option 'b

The above reads poorly to me.  Something that should be left to docstrings themselves maybe?

**Comment by danabr** [comment]
I experimented a bit with this a few weeks ago (using the syntax you suggest here). It worked OK for my needs, although you have to handle problems such as multiple val declarations for the same function.

Another option I played with is to put the type after the let binding. That would allow us to type any let binding at any level, not just top level function definitions:
````
let add x y : [int, int] -> int = x + y

let map Some a f : [option 'a, (['a -> 'b])]  -> option 'b
let map _ _ = None

type foo = int
let top_level_value : foo = 3
````
The downside is that you would have to inspect the type declaration itself to find out which type variables are used. Also, it might seem weird or inconsistent to only assign a type spec to one of the variants.

Finally, I've pondered more about the syntax of function type declarations. I think I've found the option I like the best is `fn int int -> int`. It is short and sweet, and you could reuse the `fn` keyword for lambdas. Reusing the examples above:
````
let add x y : fn int int -> int = x + y

let map Some a f : fn (option 'a)  (fn 'a -> 'b)  -> option 'b
let map _ _ = None
````

**Comment by danabr** [comment]
And of course, a third option is to let you annotate function arguments and arbitrary expressions, yielding:
````
let add x:int y:int = x + y : int
let map (Some a) : (option 'a)  f : (fn 'a -> 'b) = Some (f a) : option 'b
let map _  _  = None
````
This has the upside that you can easily specify types only for the arguments that you want to specify types for. In the other alternatives, you have to invent a type variable for that.

**Comment by j14159** [comment]
I like the `fn a b -> c` syntax, especially the re-use possibilities for lambdas.

The issue I have with the trailing types and and type-per-parameter is keeping track of where the spec is.  Having said that, it would be valuable to be able to spec bindings inside of functions as well.  I do like the ability to ignore parts of specs, like if I want to leave `f`'s type up to the inferencer maybe use `_` for `f`'s type:

    val map 'a 'b: fn (option 'a) _ -> option 'b
    let map Some a f = Some (f a)
    let map _ _ = None

What I like about the `val` approach is that we could reuse it pretty easily for signatures/interfaces later and I think throwing a type error on duplicate specs wouldn't be particularly hard.  Having said that, I see value in supporting both, potentially, e.g.

    val add2: fn int -> int
    let add2 x =
      let add a: int b: int -> int = a + b in
      add x 2

Obviously an overwrought example there ;)

What do you think?

**Comment by mrkaspa** [comment]
why val? why no a haskell/elm style?

```
add2 : int -> int
let add2 x =
	add : int -> int -> int
  let add a b = a + b in
  add x 2
```

**Comment by j14159** [comment]
@mrkaspa mostly I was thinking of consistency (e.g. how all bindings need a leading `let`) and a little worried that without a leading `val` (or something similar) we'd get ourselves back into a situation where we need significant whitespace again.  If it makes sense and works for parsing without a leading `val` I have no problem with dropping it :)

I also realized this morning that we might want to use `spec` to overlap with Erlang.  This is a little more consistent with how we'd type functions for dialyzer as well, e.g.

    spec map 'a 'b : fn (fn 'a -> 'b) (option 'a) -> option 'b
    let map f None = None
    let map f Some a = Some (f a)

Bit of a shame that `spec` and `let` don't line up though.

**Comment by mrkaspa** [comment]
I like the spec syntax pretty similar to elixir's one

**Comment by j14159** [comment]
Closing this for now as we have specifications with `val` in v0.2.8 via @lepoetemaudit 's work, [documented here in the tour](https://github.com/alpaca-lang/alpaca/blob/master/Tour.org#functions).

**Comment by j14159** [comment]
Per @danabr earlier:

> And of course, a third option is to let you annotate function arguments and arbitrary expressions

I think there's room to continue this discussion, adding this functionality.
