### ISSUE TITLE
Is there a way to interoperate with Elixir modules?

### ISSUE THREAD

**Issue by mrkaspa** [alpaca-lang/alpaca#159]

**Comment by lepoetemaudit** [comment]
Sure! Seems like there are three things here though:

1. Calling Alpaca from Elixir

This is easy - Alpaca modules are just the name you give them prefixed with underscore, so if your Alpaca module is called 'my_module' you can call it from Elixir like:

```elixir
:alpaca_my_module.a_function("an argument")
```

Functions you intend Elixir/Erlang/LFE etc. to use should probably have type guards so you at least get a runtime check that you're passing the right thing into your type-safe Alpaca code.

2. Calling Elixir from Alpaca

This is theoretically very easy too - just use the `beam` FFI call and pattern match on the return values ([as described in the tour] (https://github.com/alpaca-lang/alpaca/blob/master/Tour.md#the-foreign-function-interface)of this).

The difficulty is that Elixir module names have the format of `Elixir.MyProject.MyModule`, and as far as I'm aware we can't currently construct atoms that look like that in Alpaca (we need to be able to quote atoms). I'll hopefully put in a PR for that soon. Remember that Elixir always prefixes generated modules with `Elixir.` as well.

3. Integrating Alpaca into an Elixir project

Elixir/Mix has the concept of 'compilers', which makes it easy to integrate other languages (the Leex/Yecc integration in Elixir is an example of a compiler). There isn't currently a compiler but it's fairly easy to wrap the rebar3 plugin. I'm hoping to create a mix compiler you can pull in as a hex dependency as a community project to make this easier.

I'm personally a big user of Elixir so very keen to make sure the interop is as smooth as it is for Erlang.

**Comment by j14159** [comment]
FWIW I'm comfortable with us adopting something like `:"a quoted atom"` and I think that's probably a relatively simple change for us to make.

**Comment by mrkaspa** [comment]
Pretty cool, I mainly use Elixir and I would like to use Alpaca from a Mix project

**Comment by j14159** [comment]
With #162 merged can we consider this issue resolved for now and maybe a different issue can be opened for a mix plugin?  We should probably think about extending docs for calling Alpaca code from Elixir and this I think probably falls under issue #79 as well.

**Comment by arkgil** [comment]
I'd be happy to implement Alpaca compiler plugin for Mix. I mainly use Elixir and I'm very interested in calling Alpaca modules in my Mix projects.

**Comment by j14159** [comment]
@arkgil iirc @lepoetemaudit is also digging into this, probably best the two of you discuss :)

**Comment by arkgil** [comment]
It looks great, thank you :)

**Comment by j14159** [comment]
Closing due to PR #162.

**Comment by phtrivier** [comment]
Has there been work on an "official" mix plugin for alpaca ?

Or, for a more "hacky" solution, assuming I'm able to compile alpaca code and put it in the `_build/..../` folder of an elixir project, is there a way to make this code available to `mix compile` ?

**Comment by lpil** [comment]
You can create a mix umbrella application and have one of the applications in the umbrella be a rebar3 project using the rebar3 plugin for Alpaca https://github.com/alpaca-lang/rebar_prv_alpaca
