### ISSUE TITLE
Suggestions for a name

### ISSUE THREAD

**Issue by tuncer** [alpaca-lang/alpaca#18]
Let's collect some suggestions for a name.

Peter Landin -> lander
Robin Milner -> ermil
Tarm (birthplace of Agner Krarup Erlang) plus ML -> tarmel or tarml
ML + erl -> merl, but merl already is a known Erlang module
lambda calculus -> lama

**Comment by j14159** [comment]
Llama's are related to camels, this language is sort of related to OCaml?

**Comment by yurrriq** [comment]
I like llama.

**Comment by tchoutri** [comment]
what about llamerl? :D

**Comment by tjweir** [comment]
Millbeam

**Comment by tuncer** [comment]
I can predict that the double l will be a problem, hence the simplified suggestion of lama, and because it's not Llambda calculus either.

**Comment by tchoutri** [comment]
@tuncer could you enlighten us more about your predictions?
Spanish language uses double ll in a lot of words are they're quite fine! :p

**Comment by tuncer** [comment]
@tchoutri llamerl doesn't roll of the tongue because of the RL but MA does.

**Comment by j14159** [comment]
Also a "Lama" is a title for a person :)

**Comment by tchoutri** [comment]
@tuncer I'm not sure about what you mean, since we may not be native speakers of the same language .

**Comment by yurrriq** [comment]
It carries a [different meaning in Spanish](https://translate.google.com/#es/en/lama%20el%20culo).

**Comment by tuncer** [comment]
@tchoutri words starting with LL will be misspelled more frequently because it's not so common and the second l is unlikely to be pronounced.

**Comment by j14159** [comment]
To tag onto @tjweir's suggestion, ML-for-Beam, MilLBeam.

**Comment by tchoutri** [comment]
thanks @yurrriq for this input :)
@tuncer that's probably why its pronunciation should be "officially" standardized :p

**Comment by tuncer** [comment]
@tchoutri it's easy: when I pronounce lama, there's less mouth mechanics (for lack of the correct term) involved. It's the L sound that in ERL that makes it so. For instance, intern is easier to pronounce than interl.

**Comment by arpunk** [comment]
@yurrriq Yea, I'd go with Llama instead.

![Llama](https://dingo.care2.com/pictures/causes/3090/3089824.large.jpg)

**Comment by j14159** [comment]
`llama` vs `lama` I like the former because not-a-person and I'd rather not appropriate a Tibetan Buddhist teacher's title for a tiny programming language - feels a bit presumptuous :)

**Comment by tuncer** [comment]
@j14159 I don't like MilLBeam, because it looks easy to misspell in mixed case, and it doesn't roll of the tongue like ermil or lama do.

**Comment by tchoutri** [comment]
@j14159 Thanks for avoiding the unnecessary cultural appropriation :heart:

**Comment by tuncer** [comment]
Lama (and lamia) are often used as female Arabic names, hence I wouldn't go so far to say that one person from Tibet has a monopoloy on the word. It's not like the name would be used in a bad way, so it wouldn't be offensive. Before you brought it up, I hadn't associated it Dalai Lama at all. However, if it will be offensive to some, we shouldn't consider it.

**Comment by tuncer** [comment]
ermil sounds like the German Murmel(tier), which is German for groundhog, and since the in the movie Bill Murray has to relive the same day in a loop, and in Erlang we write a lot of recursive functions, I like the name ermil :).

**Comment by tchoutri** [comment]
Yeah but the groundhog isn't the mascot animal of Erlang or ML :p
whereas Llamerl is quite straightfoward, with clear references to the noble animal and the language, and finally no possible sexualisation of its name (although I like MLFE a lot).

**Comment by tuncer** [comment]
I'm unaware of ML or Erlang mascots, and we don't necessarily have to think of a groundhog when saying ermil. Also, it gives credit to Milner plus Erlang, is short, sounds like ML, and it's not culturally delicate/offensive.

**Comment by tuncer** [comment]
__tarmel__: Agner Krarup Erlang was born in Tarm, so one could consider Tarmel as a word play combination of Erlang's namesake's birthplace plus mel from ML.

**Comment by tuncer** [comment]
__tarmel__: Agner Krarup Erlang was born in Tarm, so one could consider Tarmel as a word play combination of Erlang's namesake's birthplace plus mel from ML. And it rolls off the tongue nicely. And tarmel almost sounds like Camel as well.

**Comment by j14159** [comment]
@tuncer in that vein, `Tarml` (like Caml, OCaml)?

**Comment by tuncer** [comment]
@j14159, sure, we can omit the `e`.

**Comment by saem** [comment]
Tyto, barn owl, eats gophers among other critters. :)

**Comment by ypaq** [comment]
nerml

**Comment by ypaq** [comment]
alpaca

**Comment by yurrriq** [comment]
I like TarML. It evokes "Turing tar pit" too :smile:

**Comment by tuncer** [comment]
ecar: e for Erlang and car for Cardelli. Luca Cardelli wrote the first ML compiler, and mlfe is a compiler. car can also be a sibling of cdr since 1958 (LISP) or 1954 (IBM-704 asm macros), if that's your first association. Short and easy to pronounce.

**Comment by j14159** [comment]
Going with "alpaca".  #alpaca-lang on freenode is setup and there's a github org with the same name I'll move the repo too once I've refactored everything for the name change.

**Comment by lpil** [comment]
Neat :)

Is there a story behind the name?

**Comment by j14159** [comment]
Same family as Camels and we have a few syntactic similarities/pull some ideas from OCaml :)
