### ISSUE TITLE
Lambdas lose their environment if defined in applications

### ISSUE THREAD

**Issue by lepoetemaudit** [alpaca-lang/alpaca#196]
In certain cases lambdas are unable to close over values in their environment, e.g. the arguments passed to an outer function.

Defining a function in  `let... in...` expression in-line in the application works, which leads me to believe lambdas are not being rewritten correctly inside applications. Similarly, a lambda previously defined can close over external scopes without issue. The below test cases demonstrates these three circumstances.

For context, I hit this when trying to chain result types (using a `|>` and `bind` sort of pattern), and being able to access the outer scope in a lambda is very useful.

```ocaml
module lambdas

val apply 'a 'b : fn (fn 'a -> 'b) 'a -> 'b
let apply f x = f x

-- Fails compilation with {bad_variable_name,lambdas,8,<<"x">>}
let useLambda x =
  apply (fn y -> x + y) 10

-- Compiles successfully
let boundLambda x =
  let lambda = (fn y -> x + y) in
  apply lambda 10

-- Compiles successfully
let useLet x =
  apply (let f y = x + y in f) 10
```

**Comment by j14159** [comment]
Thanks for finding this.  I haven't dug in yet but I bet we're not rewriting the symbols inside contained lambdas properly during the AST generation stage.
