### ISSUE TITLE
Call Elixir

### ISSUE THREAD

**Issue by ShalokShalom** [alpaca-lang/alpaca#207]
Can i call Elixir code as well?

**Comment by OvermindDL1** [comment]
Sure, just prepend the module **atom** name with `Elixir.` for any given elixir module.

**Comment by lepoetemaudit** [comment]
@ShalokShalom to elaborate on what @OvermindDL1  said, yes, you certainly can. You have to do an FFI call (i.e. a `beam` expression) https://github.com/alpaca-lang/alpaca/blob/master/Tour.md#the-foreign-function-interface. Bear in mind that Elixir prefixes all of its modules with `Elixir`, so you have to do something like this:

`beam :"Elixir.IO" :puts ["Hello world!"] with _ -> :ok`

Integrating Alpaca into Elixir projects is a little trickier however, but in future should be pretty straightforward.

If possible please don't open issues for general questions - we're on IRC (#alpaca-lang on freenode) and we're always happy to answer questions there!

**Comment by ShalokShalom** [comment]
I was more asking because Erlang is mentioned in the Readme. You may like to include Elixir as well. Thy
