### ISSUE TITLE
Writing Alpaca with Rebar3; not working!

### ISSUE THREAD

**Issue by etnt** [alpaca-lang/alpaca#209]
Hi,

I tried to follow the description in the chapter "Writing Alpaca with Rebar3".
But what is supposed to happen after "rebar3 shell"?
The example is not compiled...
Running on Mac btw

`$ rebar3 shell
===> Verifying dependencies...
Erlang/OTP 19 [erts-8.3] [source] [64-bit] [smp:8:8] [async-threads:0] [hipe] [kernel-poll:false] [dtrace]

Eshell V8.3  (abort with ^G)
1> alpaca_example:add(2, 6).
** exception error: undefined function alpaca_example:add/2

$ ls src
example.alp

$ cat rebar.config 
{plugins, [
        {rebar_prv_alpaca, ".*", {git, "https://github.com/alpaca-lang/rebar_prv_alpaca.git", {branch, "master"}}}
    ]}.

{provider_hooks, [{post, [{compile, {alpaca, compile}}]}]}.
{erl_opts, [debug_info]}.
{deps, []}.`

**Comment by lepoetemaudit** [comment]
Hi @etnt, everything looks good in your config, but it doesn't look like it ran the Alpaca compiler stage for some reason. You you try running `rebar3 alpaca compile` and seeing what outputs?

**Comment by etnt** [comment]
Not much:

$ rebar3 alpaca compile
===> Verifying dependencies...

**Comment by lepoetemaudit** [comment]
Hmm. I just tried with your config verbatim and it worked - the current master on the rebar plugin isn't so verbose with message so it's not too surprising it's not outputting much. My guess is you 're not exposing the add function?

```elm
module example

export add

let add x y = x + y
```

**Comment by etnt** [comment]
$ cat src/example.alp 
module example

export add/2

let add x y = x + y

**Comment by lepoetemaudit** [comment]
I think I see the problem - rebar3 requires certain files to be present in order to initiate compilation. I'd start with a fresh rebar3 app - do something like this:

`rebar3 new app alpexample`

Then replace the created `rebar.config` with the example one, and add your `.alp` file into the `src` folder.

**Comment by etnt** [comment]
Ok, got it to work now.
The problem was that I had removed the app.src file from my src dir.

Another question: why is the compiled moduled prefixed with 'alpaca_'?

**Comment by NobbZ** [comment]
It avoids clashes with already existing erlang modules. The same reason why elixir has children to prefix with `Elixir.`.

**Comment by lepoetemaudit** [comment]
NobbZ beat me to it :) as this is working I'm going to close, but thanks for trying Alpaca! A much improved rebar plugin and new version of Alpaca are well underway so we'll work on improving the documentation too. Perhaps we'll have a tool that creates a template project (or get that added to rebar itself).
