### ISSUE TITLE
Qualified import

### ISSUE THREAD

**Issue by lpil** [alpaca-lang/alpaca#221]
Hello!

I prefer to qualify my imported functions by default as I believe that the module name on the call makes it much clearer where functions are defined. Is there a way to import functions in a qualified way? It seems that `import module.function` permits both qualified and unqualified calls of the imported function.

Cheers,
Louis

**Comment by j14159** [comment]
Given:

    mod a
    export add
    let add x y = x + y

Then this is OK:

    mod b
    import a.add
    let foo () =
      -- both of these will work:
      let _ = a.add 1 1 in
      let _ = add 1 1 in
      :done

And this is OK:

    mod b

    let foo () =
      -- qualified only since there's no import:
      let _ = a.add 1 1 in
      :done

But this will fail to compile:

    mod b

    let foo () =
      -- works:
      let _ = a.add 1 1 in
      -- should fail because no import:
      let _ = add 1 1 in
      :done

Importing only works for exported functions and is a way to drop qualification, it won't expose an un-exported function from, for example, `a`.  Does this run counter to what you're after?

**Comment by lpil** [comment]
Oops! Too much Haskell and Elm. I presumed some sort of import statement is always required. Thanks!

**Comment by lpil** [comment]
Is it possible to alias a long module name? Something like `alias my_app_data_user as user` ?

**Comment by j14159** [comment]
Not at present, no.  I'm totally fine with seeing that feature added though it'd be low priority for my own personal work queue.  Probably not a huge change, can probably accomplish this with a rewrite in `alpaca_ast_gen.erl`.

**Comment by OvermindDL1** [comment]
> Is it possible to alias a long module name? Something like `alias my_app_data_user as user`?

OCaml's syntax for that would be much nicer:

```ocaml
module User = My_app_data
```

**Comment by lpil** [comment]
I didn't want to imply this would go as far as a first module system :)

**Comment by OvermindDL1** [comment]
> I didn't want to imply this would go as far as a first module system :)

Aww, but the beam VM would so very well support first-class modules.  ^.^

**Comment by j14159** [comment]
> Aww, but the beam VM would so very well support first-class modules. ^.^

I'm working on a reading list for this :)  (mostly because I have a lot to learn)

**Comment by OvermindDL1** [comment]
> I'm working on a reading list for this :) (mostly because I have a lot to learn)

Oh if you have questions about first class modules, higher polymorphic modules, Functors, or basically anything else in OCaml, I can explain in detail.  :-)

HPT's (like OCaml's Module system) is *significantly* more powerful than essentially all of Haskell's typing system alone as it can emulate, for example, even typeclasses (as a *VERY* simple example) but significantly more performant in compilation time (and with no runtime costs over standard dispatch, which is optimizable out).  All while HPT's have a singular syntax representation unlike Haskell's type system horrors.  :-)

**Comment by j14159** [comment]
> I can explain in detail. :-)

I may yet take you up on that :)  Currently I'm still intrigued by the possibilities in 1ML but need to dig in more.  I'm thinking we do need something that synthesizes Erlang modules out of Alpaca sig+module combinations, it's just not at the *very* top of my list yet :D  (algebraic effects and the FFI are other large-scale/scope things to figure out too, along the lines of discussion in #7).
