### ISSUE TITLE
Type error with option.flatten definition

### ISSUE THREAD

**Issue by lpil** [alpaca-lang/alpaca#229]
Given orElse already exists in the module:

```elm
val orElse 'a : fn 'a (option 'a) -> 'a
let orElse default op =
  match op with
  | None -> default
  | Some value -> value
```

And I want a function flatten with the this behaviour:

```elm
flatten (Some (Some 42)) == (Some 42)
flatten (Some None) == None
flatten None == None
```

I think I should be able to define it like so:
```elm
let flatten op =
  orElse None op
```

But it does not type check
```erlang
===> Alpaca compile error:
(╯°□°）╯︵ ┻━┻ {cannot_unify,option,104,
              {adt,<<"option">>,option,
                   [{"a",{unbound,t22,0}}],
                   [{t_adt_cons,"Some"},{t_adt_cons,"None"}]},
              t_unit}
```
  
Side note: I wanted to make a PR adding a reproduction of the problem but wasn't sure where. Do the `test_modules` get compiled as part of the testing process as integration style tests?

**Comment by j14159** [comment]
`src/alpaca.erl` would be where to add this, loading the code from an Alpaca source file in `test_files/`.  I think an argument could be made that these should be integration tests but I'm not super dogmatic about that yet :)

Interesting that the typer is inferring the unit type somewhere in there, quite curious to see where the bug lies!

**Comment by j14159** [comment]
I figured it out.  Type tags/constructors, e.g. `None` always eagerly consume the next arg.  So this:

```ocaml
let flatten op = orElse None op
```

Should actually be:

```ocaml
let flatten op = orElse (None) op
```

At a minimum the typer should throw an error about incorrect arity when it sees `None op` instead of `(None) op`.
