### ISSUE TITLE
Can't find a way to contact the creator/mantainers of alpaca :)

### ISSUE THREAD

**Issue by marianoguerra** [alpaca-lang/alpaca#248]
Hi!

I'm giving a talk on codebeam SF titled "Implementing Languages on the BEAM" and I would like to have a wide range of examples and experiences implementing languages on the beam. Could you provide me with mail addresses or ways to contact the creator/maintainers of alpaca so I can send some questions?

you will be rightfully attributed where/if you want :)

**Comment by lpil** [comment]
I'm not one of the maintainers, but Jeremy can be found on twitter here -> https://twitter.com/j14159

I also [dabble](https://github.com/lpil/gleam/) in implementing languages on the BEAM if you'd like to chat :)

**Comment by j14159** [comment]
What @lpil said and also we have a mailing list where I'd be happy to answer questions and discuss:  https://groups.google.com/forum/#!forum/alpaca-lang

Looking forward to seeing the video of your talk!

Will close this issue for now but feel free to reopen if necessary for further discussion.
