### ISSUE TITLE
clarify - nominal or structural type system

### ISSUE THREAD

**Issue by ORESoftware** [alpaca-lang/alpaca#265]
Sorry if I missed this in the readme - but if it's not there it should be added - does Alpaca use a nominal type system or structural?

**Comment by j14159** [comment]
It would probably be most appropriate to call it a structural type system but I'd caution that without a notion of subtyping (as yet), that might not have a ton of meaning for lots of people 😄 As mentioned [in other places](https://github.com/alpaca-lang/alpaca/issues/251#issuecomment-411104084) I've been considering 1ML for a sort of structural approach to subtyping as well.

**Comment by ORESoftware** [comment]
What do you mean by "subtyping"?
