### ISSUE TITLE
is the project dead

### ISSUE THREAD

**Issue by SuheylZ** [alpaca-lang/alpaca#271]

**Comment by SuheylZ** [comment]
The very first time i heard about this language is when reading Gleam QA. the last commit was made 5 years ago and there is no ommercial work being done using it. Google searches return motly about a Camel and only one link about the language which is this Github repo off course. so ... is it dead ?

**Comment by kvakvs** [comment]
See https://gleam.run/

**Comment by SuheylZ** [comment]
what about it? gleam is 

> See https://gleam.run/

i didn't understand, Gleam is a separate language. I'm tallying about this one

**Comment by lpil** [comment]
Hello! I believe development has stopped, yes. Gleam is somewhat a spiritual successor to Alpaca. I was previously working on the standard library and decided to continue my work in Gleam.
