### ISSUE TITLE
edoc spec extraction

### ISSUE THREAD

**Issue by tuncer** [alpaca-lang/alpaca#36]
We might want to look into how edoc extracts specs of functions (which it then includes in the generated documentation).

**Comment by OvermindDL1** [comment]
If you want to know how you can see my code for it, this extracts types, specs, and opaques (it is not pretty, but it works, and this is Elixir but easy enough to convert as it is pure erlang modules):  https://github.com/OvermindDL1/typed_elixir/blob/master/lib/typed_elixir.ex#L228-L243
