### ISSUE TITLE
Consider prefixing compiled Alpaca modules

### ISSUE THREAD

**Issue by lepoetemaudit** [alpaca-lang/alpaca#75]
When Elixir compiles modules, it prefixes the generated module name with 'Elixir.' ([more info here](http://elixir-lang.org/crash-course.html#adding-elixir-to-existing-erlang-programs)). This means that any modules compiled with Elixir don't risk clashing with Erlang ones, and it keeps the Elixir standard library nicely namespaced. From within Elixir code, you don't need to use the prefix.

I believe the same would be useful in Alpaca - perhaps automatically prefix every generated module with `alpaca_`. It means a bit of extra typing when calling from the Erlang side, but it also means we could give nice names to Alpaca standard library modules like `string` instead of having to import e.g. `alpaca_string` within Alpaca code.

**Comment by j14159** [comment]
Good idea.  

Probably only requires changes to `alpaca_codegen.erl` to rewrite references to other modules in function applications and in the rebar plugin for filename outputs.

I'm working on #56 at the moment and want to get to imports next - if you feel like taking a crack at this I'm more than happy to help out/answer any questions that come up!

**Comment by lepoetemaudit** [comment]
I'll make it so - thanks.
