### ISSUE TITLE
Double line breaks in expressions fail to compile

### ISSUE THREAD

**Issue by ypaq** [alpaca-lang/alpaca#82]
It would be desirable to be able to split code up with several line breaks. This is an example where double line breaks `\n\n` are significant and cause a compilation error.

```
alpaca:compile({text, [<<"module a \n\nf a = let add x = x + x in\n\nadd a a\n\n">>]}).
```

**Comment by lepoetemaudit** [comment]
I checked OCaml's parser, which has a broadly similar syntax to Alpaca's - ML but non-whitespace significant (the above notwithstanding). In OCaml, top level phrases have to be terminated with `;;` to avoid the above issue, but they can be elided in certain cases, such as before an `open` or `let` - [some more info here.](https://ocaml.org/learn/tutorials/structure_of_ocaml_programs.html#Usingandomittingand)

With that in mind, I can think of three options:

1. We introduce `let` at the top level (and possibly optional terminator `;;`) and follow much the same parsing rules as OCaml.
2. We switch to whitespace significant rules à la Haskell, Elm and F#
3. We can be a bit less drastic than option 2 and simply require that top level function bodies are indented - they terminate either at EOF or the next non-empty line that begins at column 1.

I think 3 would solve this particular issue in a fairly non-intrusive way, although it might have other side-effects I haven't considered.

**Comment by j14159** [comment]
I like options 1 and 2 a lot more than 3 to be honest.  3 feels like we're going in python's direction where right now we're just treating `\n\n` as punctuation, seems simpler to me.  How far away from #2 are we do you think?  Any big inconsistencies or horribleness?

I'm also ok with seriously considering introducing top-level `let`s and then sort of privileging `module`, `import`, `export`, `let` et al as signifying the major AST nodes for the parser.

To boil it down, my current opinion is:
- `let` is a little noisy but far from terrible.  Does seem one way of simplifying things with a bit of an invasive fix in the immediate term.
- I'm ok with significant whitespace if it's limited to `\n` being significant (it being treated as punctuation).
- there's going to be a code formatter.

I'm pretty open to changing everything but the formatter :)

**Comment by lepoetemaudit** [comment]
I have a branch now with the new 'let' syntax and whitespace significance removed, and all tests passing - https://github.com/alpaca-lang/alpaca/compare/master...lepoetemaudit:top-level-let-ignore-ws. I'd like to add some specific test coverage around the break handling. The break inference happens in `alpaca_scanner.erl` and it's pretty straight forward, yet it seems to work in every circumstance I can think of (I didn't have to alter the tests apart from to add 'let' in front of top level defines).

A code formatter would be very good indeed.
