### ISSUE TITLE
Referring to missing types does not generate an error

### ISSUE THREAD

**Issue by j14159** [alpaca-lang/alpaca#91]
module x

    type a = int | b

This doesn't generate an error about an undefined type `b` and it should.

Thanks to @danabr for pointing this out in IRC

**Comment by danabr** [comment]
Referring to an unknown type variable should also be an error. Currently, the compiler let's this through:
````
type baz 'a = Baz 'c

let woot Baz _ = :ok
````

Should we squash that one at the same time, or would you prefer a separate issue?

**Comment by j14159** [comment]
Seems like part of the same issue to me, thanks for adding this!
