### ISSUE TITLE
Boolean operator support

### ISSUE THREAD

**Issue by danabr** [alpaca-lang/alpaca#97]
As far as I can tell, we cannot do things like ``(x == 1) || (y < 4)`` and ``(x == 1) && (y < 4)``.

**Comment by Licenser** [comment]
I've put in some logic in #182 but I think it's a bit wring given it does not short curcuite. It might be better to implement `||` and `&&` in something like core-alpaca if that exists?

**Comment by yurrriq** [comment]
Perhaps `andalso` and `orelse` are more appropriate.

**Comment by Licenser** [comment]
That is what I thought too, but it turns those are not functions in erlang. When I thought about it, it made sense as you can't implement short circuting and/or with a function.

Basically I think there are three options:
1) don't short circuit - as done in #182 
2) generate the code for them as part of the code generation (i.e. turn `||` into something like `case Left of true -> true; false -> Right end`)
3) since alpaca can define infix operators, define it in alpaca itself

Personally 3 feels like the best option but I'm not sure if that has implications that I don't see.

**Comment by yurrriq** [comment]
Ah, right. Option 3 sounds good to me.

**Comment by Licenser** [comment]
Well I'm stupid, implementing them as infix functions will have the same problem as `:and` and `:or` -.-

**Comment by j14159** [comment]
@Licenser nobody is stupid, just at various points in figuring out or learning what to do :)

**Comment by j14159** [comment]
(e.g. I have no idea here at present)

**Comment by yurrriq** [comment]
Perhaps the `case` idea is solid. Later I'd like like to examine the Core Erlang generated by something like this:

```erlang
'&&'(A, B) ->
  A andalso B.
```

**Comment by j14159** [comment]
Closing per PR #182 for now.

**Comment by yurrriq** [comment]
#### `foo.erl`

```erlang
-module(foo).

-export(['&&'/2]).

'&&'(A, B) ->
    A andalso B.
```

#### `foo.core`

```fish
erlc +to_core foo.erl
```

```erlang
module 'foo' ['&&'/2,
	      'module_info'/0,
	      'module_info'/1]
    attributes []
'&&'/2 =
    %% Line 5
    fun (_cor1,_cor0) ->
	%% Line 6
	( case _cor1 of
	    ( <( 'true'
		 -| ['compiler_generated'] )> when 'true' ->
		  _cor0
	      -| ['compiler_generated'] )
	    ( <( 'false'
		 -| ['compiler_generated'] )> when 'true' ->
		  'false'
	      -| ['compiler_generated'] )
	    ( <_cor2> when 'true' ->
		  ( call ( 'erlang'
			   -| ['compiler_generated'] ):( 'error'
							 -| ['compiler_generated'] )
			(( {( 'badarg'
			      -| ['compiler_generated'] ),_cor2}
			   -| ['compiler_generated'] ))
		    -| ['compiler_generated'] )
	      -| ['compiler_generated'] )
	  end
	  -| ['compiler_generated'] )
'module_info'/0 =
    fun () ->
	call 'erlang':'get_module_info'
	    ('foo')
'module_info'/1 =
    fun (_cor0) ->
	call 'erlang':'get_module_info'
	    ('foo', _cor0)
end
```

**Comment by Licenser** [comment]
That is pretty much the same thing that the `&&` now does other that it doens't do the 3rd condition OTOH if either of them is not a boolean we get a compile time error from what I understand :)
