### ISSUE TITLE
VIm syntax highlighting

### ISSUE THREAD

**Issue by lpil** [alpaca-lang/alpaca#98]
Hello! This would be ace for us vim users.

You're probably too busy (and an emacs user) to work on this, but I thought I'd note this down for the future :)

**Comment by lepoetemaudit** [comment]
I might have a quick go at this at some point. I hop a lot between vim and vs code.

**Comment by lpil** [comment]
Marvellous. I may have a stab too- not writen vim syntax highlighting before.

**Comment by ahammel** [comment]
The [elm-vim](https://github.com/ElmCast/elm-vim) syntax file seems like a good place to start

**Comment by alinpopa** [comment]
I know it's just a workaround, but this is what I'm currently doing:
```
autocmd BufNewFile,BufRead *.alp set filetype=ocaml
```

**Comment by lepoetemaudit** [comment]
I finally put together a vim plugin here: https://github.com/lepoetemaudit/alpaca_vim - feedback welcome!

**Comment by lpil** [comment]
Great work, thanks Dave.
